tags:
  - name: wines
    description: Wines API

paths:
  # [GET] wines
  /wines:
    get:
      tags:
        - wines
      summary: API to get list of wine
      parameters:
        - name: name
          in: query
          description: Wine name search key
          type: string
        - name: minPrice
          in: query
          description: Minimum price of wine
          type: string
        - name: maxPrice
          in: query
          description: Maximum price of wine
          type: string
        - name: minRating
          in: query
          description: Minimum rating of wine
          type: string
        - name: maxRating
          in: query
          description: Maximum rating of wine
          type: string
        - name: minNoRatings
          in: query
          description: Minimum number of ratings
          type: string
        - name: maxNoRatings
          in: query
          description: Maximum number of ratings
          type: string
          
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

schemes:
  - https
  - http
