tags:
  - name: wines
    description: Wines API

paths:
  # [GET] wines
  /wines:
    get:
      tags:
        - wines
      summary: API to get list of wine
      parameters:
        - name: grapes
          in: query
          description: Grape names (Eg: Malbec,Merlot ..), Multiple names can be added separating by a comma 
          type: string
        - name: wineStyles
          in: query
          description: Wine styles (Eg: Argentinian Malbec,Spanish Red ..), Multiple wine styles can be added separating by a comma 
          type: string
        - name: foodPairings
          in: query
          description: Food pairings (Eg: Poultry, Veal ..), Multiple food pairings can be added separating by a comma 
          type: string
         - name: countryCodes
          in: query
          description: Country codes (Eg: in, us ..), Multiple country codes can be added separating by a comma 
          type: string
        - name: regions
          in: query
          description: (Eg: Toscana, Piemonte ..), Multiple country codes can be added separating by a comma 
          type: string
        - name: orderBy
          in: query
          description: (Eg: discount_percent, ratings_average, price, ratings_count)
          type: string
        - name: order
          in: query
          description: (Eg: asc, desc)
          type: string
        - name: minPrice
          in: query
          description: Minimum price of wine
          type: string
        - name: maxPrice
          in: query
          description: Maximum price of wine
          type: string
        - name: minRating
          in: query
          description: Minimum rating of wine
          type: string
        - name: minNoRatings
          in: query
          description: Minimum number of ratings
          type: string
        - name: maxNoRatings
          in: query
          description: Maximum number of ratings
          type: string
          
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

schemes:
  - https
  - http
